// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/feishu/fields': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feishu/fields.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feishu/fields.post').default>>>>
    }
    '/api/feishu/records': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feishu/records.post').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test.get').default>>>>
    }
    '/api/url-expand': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/url-expand.post').default>>>>
    }
    '/api/url-expand/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/url-expand/batch.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}